# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1 # 2.1 config required to use orbs

orbs:
  aws-ecr: circleci/aws-ecr@7.3.0 # invoke the AWS ECR orb
  aws-ecs: circleci/aws-ecs@2.2.1 # invoke the AWS ECS orb
  aws-cli: circleci/aws-cli@2.0.6
jobs:
  ecr-login-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - aws-ecr/ecr-login:
          region: AWS_REGION 
          aws-access-key-id: AWS_ACCESS_KEY_ID 
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY 
          account-url: AWS_ECR_ACCOUNT_URL 
  build-and-push-job:
    docker:
      # replace with your preferred image
      - image: cimg/base:stable
    steps:
      - aws-ecr/build-and-push-image:
          account-url: AWS_ECR_ACCOUNT_URL_P 
          aws-access-key-id: AWS_ACCESS_KEY_ID 
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY  
          path: ./backend/ 
          region: AWS_REGION 
          repo: ECR_REPOSITORY 
          tag: CIRCLE_SHA1 
workflows:
  build-and-deploy:
    
    jobs:
      - ecr-login-job
      - build-and-push-job
      - aws-ecr/build-and-push-image: # orb built-in job
          account-url: AWS_ECR_ACCOUNT_URL
          repo: '${ECR_REPOSITORY}'
          tag: '${CIRCLE_SHA1}'
          path: ./backend/
          aws-access-key-id: AWS_ACCESS_KEY_ID
          aws-secret-access-key: AWS_SECRET_ACCESS_KEY
          region: AWS_REGION
      - aws-ecs/deploy-service-update: # orb built-in job
          requires:
            - aws-ecr/build-and-push-image
          family: '${ECS_SERVICE}'
          cluster-name: '${ECS_CLUSTER}'
          container-image-name-updates: 'container=${ECR_REPOSITORY},tag=${CIRCLE_SHA1}' 
